### PR TITLE
Revert "OCPBUGS-3783: Update dnsPolicy to allow consistent resolution of the internal LB"

### PR DESCRIPTION
**Pull request by dgoodwin**
Reverts openshift/cluster-version-operator#920

Just a wild guess test revert for https://issues.redhat.com/browse/OCPBUGS-11591

### CODE REVIEW

**Comment by dgoodwin** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade 3

**Comment by petr-muller** [comment]
:scream:

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by dgoodwin** [comment]
/hold

Thank you for the quick lgtm, holding as I really doubt this is it, but we'll know soon.

**Comment by dgoodwin** [comment]
/close

Problem visible in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-version-operator-925-ci-4.14-e2e-gcp-ovn-upgrade/1646514170977325056

**Pull request closed without merging**
