### PR TITLE
Bug 2005407: Changing the ClusterNotUpgradeable alert to info

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
/retest
/lgtm
/hold

For additional review from @jottofar or @wking

**Comment by LalatenduMohanty** [comment]
@wking @jottofar  I will merge the PR if I do not hear from you in next 24 hours.

**Comment by jottofar** [comment]
LGTM

**Comment by LalatenduMohanty** [comment]
ci/prow/e2e-agnostic-upgrade has passed before. 

/override ci/prow/e2e-agnostic-upgrade

**Pull request merged**
