### PR TITLE
OTA-1169: deps: bump openshift/api and k8s.io/client.go

### PR DESCRIPTION
**Pull request by petr-muller**
Created with:

```
$ go get github.com/openshift/api
$ go get k8s.io/client-go@v0.29.0
$ go mod tidy
$ go mod vendor
```

I needed to bump the k8s.io/client.go as well because without that bump
I was getting:

```
go: github.com/openshift/cluster-version-operator/pkg/cvo imports
	k8s.io/client-go/kubernetes/scheme imports
	k8s.io/api/flowcontrol/v1alpha1: module k8s.io/api@latest found (v0.29.0), but does not contain package k8s.io/api/flowcontrol/v1alpha
```

### CODE REVIEW

**Comment by petr-muller** [comment]
```
   * could not run steps: step e2e-agnostic-operator failed: "e2e-agnostic-operator" post steps failed: failed to create or restart e2e-agnostic-operator-ipi-deprovision-deprovision pod: unable to create pod: Internal error occurred: resource quota evaluation timed out 
```

/retest
Looks like build05 had a hiccup, from https://prow.ci.openshift.org/?cluster=build05 it looks it may be temporary

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
openshift/release#47783 merged.

/test lint

**Comment by petr-muller** [comment]
/hold

This saw more failures than I feel comfortable with, I want to look at results before it merges even if the last retest is green

**Comment by petr-muller** [comment]
Looking at https://prow.ci.openshift.org/pr-history/?org=openshift&repo=cluster-version-operator&pr=1022:

- azure issue [1](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1022/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-operator/1747696918672183296) [2](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1022/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1747696918709932032)
- build05 issue [1](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1022/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-operator/1747671965205794816) [2](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1022/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn-upgrade-into-change/1747671965247737856) [3](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1022/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn-upgrade-out-of-change/1747671965272903680) [4](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1022/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1747671965218377728)
- installation failure, does not seem CVO-related [1](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1022/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn-upgrade-into-change/1747696918751875072)

So no actual test failure, just a single installation fail that seems unrelated to CVO. Looks good to me.

**Comment by petr-muller** [comment]
/hold cancel
/label no-qe

Labeling as no-qe because there is no new functionality. I do not consider this bump risky enough to do a dedicated regression run before merge (it is also early in the cycle).

**Pull request merged**
