### PR TITLE
OTA-1160: pkg/cvo/reconciliation_issues: Publish ClusterOperator transitionStart

### PR DESCRIPTION
**Pull request by wking**
Allow ClusterVersion `status` consumers to make their own decisions about how long to wait before complaining about a slow-to-update ClusterOperator.

### CODE REVIEW

**Comment by wking** [comment]
Testing in Cluster Bot via `launch 4.16,openshift/cluster-version-operator#1044 aws,techpreview` ([logs][1]), I sent the cluster back to 4.16.0-ec.5 with:

```console
$ oc adm upgrade --force --allow-explicit-upgrade --to-image quay.io/openshift-release-dev/ocp-release@sha256:f5c9cf5a461434e775af2b946fc2a8aee7240f5b05d4141a588e527adcad7af9
```

Maybe I didn't need to `--force` that?  Anyhow, I let it run for a bit, until etcd completed:

```console
$ oc adm upgrade
info: An upgrade is in progress. Working towards 4.16.0-ec.5: 113 of 952 done (11% complete), waiting on kube-apiserver
...
```

Then I turned around and went back to my original release images (I had to `--force` this time, because CI releases are unsigned):

```console
$ oc adm upgrade --force --allow-upgrade-with-warnings --allow-explicit-upgrade --to-image registry.build03.ci.openshift.org/ci-ln-cm7dfnt/release@sha256:370d219ae7612d27ac08ab6de38e452c71bb4f770c692577fdd4493242ff3efd
```

And shortly after, here's the CVO waiting on `etcd` and `kube-apiserver` giving us start-times:

```console
$ date --utc --iso=m
2024-04-25T04:50+00:00
$ oc get -o json clusterversion version | jq -r '.status.conditions[] | select(.type == "ReconciliationIssues") | .message | fromjson'
{
  "message": "Cluster operators etcd, kube-apiserver are updating versions",
  "children": [
    {
      "message": "[Cluster operator etcd is updating versions, Cluster operator kube-apiserver is updating versions]",
      "children": [
        {
          "message": "Cluster operator etcd is updating versions",
          "children": [
            {
              "message": "cluster operator etcd is available and not degraded but has not finished updating to target version"
            }
          ],
          "effect": "None",
          "manifest": {
            "originalFilename": "0000_20_etcd-operator_07_clusteroperator.yaml",
            "group": "config.openshift.io",
            "kind": "ClusterOperator",
            "name": "etcd"
          },
          "transitionStart": "2024-04-25T04:50:25.572524285Z"
        },
        {
          "message": "Cluster operator kube-apiserver is updating versions",
          "children": [
            {
              "message": "cluster operator kube-apiserver is available and not degraded but has not finished updating to target version"
            }
          ],
          "effect": "None",
          "manifest": {
            "originalFilename": "0000_20_kube-apiserver-operator_07_clusteroperator.yaml",
            "group": "config.openshift.io",
            "kind": "ClusterOperator",
            "name": "kube-apiserver"
          },
          "transitionStart": "2024-04-25T04:50:25.572311511Z"
        }
      ]
    }
  ],
  "effect": "None"
}
```

And a bit later, when `kube-apiserver`  (which had never gotten all the way through to 4.16.0-ec.5) had completed, just waiting on `etcd`:

```console
$ oc get -o json clusterversion version | jq -r '.status.conditions[] | select(.type == "ReconciliationIssues") | .message | fromjson'
{
  "message": "Cluster operator etcd is updating versions",
  "children": [
    {
      "message": "cluster operator etcd is available and not degraded but has not finished updating to target version"
    }
  ],
  "effect": "None",
  "manifest": {
    "originalFilename": "0000_20_etcd-operator_07_clusteroperator.yaml",
    "group": "config.openshift.io",
    "kind": "ClusterOperator",
    "name": "etcd"
  },
  "transitionStart": "2024-04-25T04:50:25.572524285Z"
}
```


[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1783339942487789568

**Comment by petr-muller** [comment]
We're definitely not breaking Hypershift with this feature-gated change
/override ci/prow/e2e-hypershift ci/prow/e2e-hypershift-conformance

**Comment by wking** [comment]
Waiving pre-merge QE for this tech-preview, currently unconsumed content.

/label no-qe

**Comment by wking** [comment]
not sure what's up with [HyperShift][1], but that job won't care about this tech-preview property.

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1044/pull-ci-openshift-cluster-version-operator-master-e2e-hypershift/1783581013897646080

**Comment by wking** [comment]
well, `e2e-hypershift-conformance` passed.  Still dunno what's going on with [the other][1].

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1044/pull-ci-openshift-cluster-version-operator-master-e2e-hypershift/1783636539935297536

**Comment by wking** [comment]
wait, I'm a root approver for this repo 🤦 :

/override ci/prow/e2e-hypershift

**Pull request merged**
