### PR TITLE
docs: Describe upgrade ordering and design

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
cross-linking:
https://github.com/openshift/cluster-kube-scheduler-operator/pull/118
https://github.com/openshift/service-ca-operator/pull/52
https://github.com/openshift/cluster-machine-approver/pull/23
https://github.com/openshift/cluster-config-operator/pull/49
https://github.com/openshift/cluster-network-operator/pull/158
https://github.com/openshift/cluster-dns-operator/pull/101

**Comment by smarterclayton** [comment]
docs only, going to force merge

**Pull request merged**
