### PR TITLE
[release-4.8] Bug 2015025: lib/resourcemerge/imagestream.go: Copy all data for new tag reference

### PR DESCRIPTION
**Pull request by vrutkovs**
Cherry-pick of #674 + #677 on release-4.8 branch

### CODE REVIEW

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by kpouget** [comment]
> cherry-pick-approved

thanks @jianlinliu :)

I think you'll need "/label cherry-pick-approved" for the tagging to work

**Comment by jianlinliu** [comment]
Ah, I was surprise why it still complain no cherry-pick-approved label. Thanks for your help.

**Pull request merged**
