### PR TITLE
OCPBUGS-41111: vendor: Update openshift/api to pick up v4.17 and v4.18 capability sets

### PR DESCRIPTION
**Pull request by wking**
Catching up with openshift/api#2022.  Generated with:

```console
$ go get github.com/openshift/api@master
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```

all using:

```console
$ go version
go version go1.22.2 linux/amd64
```

### CODE REVIEW

**Comment by wking** [comment]
Sanity check on [e2e-agnostic-ovn][1] looks good:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1086/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1833977761480314880/artifacts/e2e-agnostic-ovn/gather-must-gather/artifacts/must-gather.tar | tar -tvz | grep clusterversions.config.openshift.io
-rw------- 1008580000/root   41631 2024-09-11 16:25 registry-build09-ci-openshift-org-ci-op-4vc3b9hy-stable-sha256-6cb3640e26d5cb9e0cced9e90dd86f06313d9a2ca8389b770541b820d2b758f1/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/clusterversions.config.openshift.io.yaml
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1086/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1833977761480314880/artifacts/e2e-agnostic-ovn/gather-must-gather/artifacts/must-gather.tar | tar -xOz registry-build09-ci-openshift-org-ci-op-4vc3b9hy-stable-sha256-6cb3640e26d5cb9e0cced9e90dd86f06313d9a2ca8389b770541b820d2b758f1/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/clusterversions.config.openshift.io.yaml | grep -A3 v4.16
                    - v4.16
                    - v4.17
                    - v4.18
                    - vCurrent
```

We'll need a vendor bump in the installer too, to get the install-config validation accepting the new sets, but we'll want that to land after this change (or the installer might accept a set in the install-config that the API wouldn't allow into ClusterVersion).

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1086/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1833977761480314880

**Comment by jiajliu** [comment]
pre-merge verify pass

/label qe-approved

**Review by petr-muller — APPROVED** [review]

**Pull request merged**
