### PR TITLE
Bug 1961341: Remove rbacv1beta1 support

### PR DESCRIPTION
**Pull request by vrutkovs**
All manifests have moved to rbacv1

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

No need to include the branch in the PR title; GitHub has that as structured information, and it clutters up `oc adm release info ...`'s rendered diffs.

/retitle Bug 1961341: Remove rbacv1beta1 support

**Comment by dhellmann** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Pull request merged**
