### PR TITLE
Bug 1872906: pkg/start: Release leader lease on graceful shutdown

### PR DESCRIPTION
**Pull request by wking**
Picking #349 and #424 back to 4.5 so we release the leader lock when we exit, which in turn allows the incoming CVO pod to pick up the leader lock and update the ClusterVersion status in a timely manner.

A number of mostly-minor manual tweaks to adjust to 4.5, which is missing #358's TLS metrics and #406 and #410's Context changes.

### CODE REVIEW

**Comment by wking** [comment]
4.6 bug is VERIFIED, so we should be unblocked here:

/bugzilla refresh

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by sdodson** [comment]
Clearing stale cherry-pick-approved. Need to figure out why these tests are all failing.

**Comment by wking** [comment]
Most recent [e2e job][1]:

```
Failing tests:

[k8s.io] [Feature:Example] [k8s.io] Secret should create a pod that reads a secret [sig-node] [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-api-machinery] CustomResourceDefinition resources [Privileged:ClusterAdmin] Simple CustomResourceDefinition getting/updating/patching custom resource definition status sub-resource works  [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
[sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] removes definition from spec when one version gets changed to not be served [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
...
[sig-storage] Projected downwardAPI should set DefaultMode on files [LinuxOnly] [NodeConformance] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
[sig-storage] Subpath Atomic writer volumes should support subpaths with secret pod [LinuxOnly] [Conformance] [Suite:openshift/conformance/parallel/minimal] [Suite:k8s]
```

I don't know how all of those could be related to this change, and just assumed they were "something generic about 4.5 or our CI infra is busted".  And [4.5 CI hasn't passed promotion in six days][2].

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/446/pull-ci-openshift-cluster-version-operator-release-4.5-e2e/1310612212561219584
[2]: https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/#4.5.0-0.ci

**Comment by wking** [comment]
[e2e][1]:

```
level=fatal msg="failed to initialize the cluster: Working towards 4.5.0-0.ci.test-2020-09-29-130214-ci-op-r6bbhq7y: 87% complete, waiting on authentication" 
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/446/pull-ci-openshift-cluster-version-operator-release-4.5-e2e/1310926766046449664

**Comment by wking** [comment]
[e2e][1]:

```
   * could not run steps: step src failed: could not wait for build: the build src failed after 1m53s with reason GenericBuildFailed: Generic Build failure - check logs for details.
```

**Comment by wking** [comment]
[e2e][1] blew up on Kube API access, with lots of `:6443: i/o timeout occurred`.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/446/pull-ci-openshift-cluster-version-operator-release-4.5-e2e/1311429260828741632

**Comment by wking** [comment]
Maybe openshift/release#12391 helped.

/retest

**Comment by wking** [comment]
All green again after openshift/release#12391.  Ready for relabeling when the patch-manger is ready.

**Comment by mfojtik** [comment]
patch-manager notes: approved as this should fix frequent 4.5->4.6 upgrade failure

**Pull request merged**
