### PR TITLE
Bug 1717619: metrics: Report reason as a label on the conditions metric

### PR DESCRIPTION
**Pull request by abhinavdahiya**
05a4e25 is cherry-pick from https://github.com/openshift/cluster-version-operator/pull/191/commits

b820c53 is cherry-pick from https://github.com/openshift/cluster-version-operator/pull/197/commits

/cc @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Wait, why is this against the master branch?

**Comment by abhinavdahiya** [comment]
This was meant to be on release-4.1

closing this for https://github.com/openshift/cluster-version-operator/pull/202

**Pull request closed without merging**
