### PR TITLE
lib/resourcebuilder/apps: Explicit mode instead of 'Generation > 1'

### PR DESCRIPTION
**Pull request by wking**
`deploymentBuilder` and `daemonsetBuilder` grow `mode` properties.  They had been using `actual.Generation > 1` as a proxy for "post-install" since 14fab0b2c8 (#26), but generation 1 is just "we haven't changed the object since it was created", not "we're installing a fresh cluster".  For example, a new Deployment or DaemonSet could be added as part of a cluster update, and we don't want special install-time "we don't care about specific manifest failures" then.

Spun out from #400 at @smarterclayton's [request](https://github.com/openshift/cluster-version-operator/pull/400/#issuecomment-655152378).

### CODE REVIEW

**Comment by wking** [comment]
Service disruption

/retest

**Comment by wking** [comment]
/override e2e-gcp-upgrade

We don't need that anymore, it's now the genrically-named e2e-upgrade.

**Comment by sdodson** [comment]
> /override e2e-gcp-upgrade
> 
> We don't need that anymore, it's now the genrically-named e2e-upgrade.

I think `/skip` is what's meant to be used when tests are removed or made non blocking but I guess that worked too.

**Comment by wking** [comment]
I tried `/skip` up [here][1], but maybe that was before the `e2e-gcp` -> `e2e` change.

[1]: https://github.com/openshift/cluster-version-operator/pull/401#issuecomment-656456038

**Pull request merged**
