### PR TITLE
Bug 2083370: Do not save desired update on load failures

### PR DESCRIPTION
**Pull request by jottofar**

### CODE REVIEW

**Comment by wking** [comment]
/retitle Bug 2083370: Do not save desired update on load failures

It's important to devs to know that this backports #776, but the more important thing for 4.10.z users is that it's fixing desired-update failure handling.

**Comment by shellyyang1989** [comment]
PR pre-merge verification passed.
/label qe-approved

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
