### PR TITLE
Fix ups from gofmt 1.19 and yamllint

### PR DESCRIPTION
**Pull request by jottofar**

### CODE REVIEW

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
CI is sad for unrelated registry.redhat.io signature store reasons.

/override ci/prow/e2e-agnostic
/override ci/prow/e2e-agnostic-operator
/override ci/prow/e2e-agnostic-upgrade-into-change
/override ci/prow/e2e-agnostic-upgrade-out-of-change

**Pull request merged**
