### PR TITLE
Using optr.queue.ShutDown directly as upstream K8s is fixed now

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Upstream pull request https://github.com/kubernetes/kubernetes/pull/77170. It is available in upstream v1.15

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by wking** [comment]
Upstream PR vendored in here with 0672262a55c (#249).

/lgtm

**Comment by sdodson** [comment]
/hold
@LalatenduMohanty can you please look into why the integration tests started failing on March 20th and haven't passed since? There was one pass on this commit so I don't know if it's this PR or a general failure.

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty can you please look into why the integration tests started failing on March 20th and haven't passed since? There was one pass on this commit so I don't know if it's this PR or a general failure.

Last time I checked the failure looked like a flake, but this time it is 
```
2020/03/27 19:16:22 Container bin-cli in pod integration completed successfully
2020/03/27 19:16:35 Container bin-hyperkube in pod integration completed successfully
2020/03/27 21:16:18 error: unable to signal to artifacts container to terminate in pod integration, triggering deletion: could not run remote command: unable to upgrade connection: container not found ("artifacts")
2020/03/27 21:16:19 error: unable to retrieve artifacts from pod integration: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
2020/03/27 21:16:19 error: could not wait for pod 'integration': it is no longer present on the cluster (usually a result of a race or resource pressure. re-running the job should help)
2020/03/27 21:16:19 No custom metadata found and prow metadata already exists. Not updating the metadata.
E0327 21:16:19.074027      13 event.go:263] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".160045c47c0d14b3", GenerateName:"", Namespace:"ci-op-gtgb1drn", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"", Namespace:"ci-op-gtgb1drn", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"CiJobFailed", Message:"Running job pull-ci-openshift-cluster-version-operator-master-integration for PR https://github.com/openshift/cluster-version-operator/pull/339 in namespace ci-op-gtgb1drn from author LalatenduMohanty", Source:v1.EventSource{Component:"ci-op-gtgb1drn", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf97b928c1e176b3, ext:7317917608909, loc:(*time.Location)(0x271e5e0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf97b928c1e176b3, ext:7317917608909, loc:(*time.Location)(0x271e5e0)}}, Count:1, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events ".160045c47c0d14b3" is forbidden: unable to create new content in namespace ci-op-gtgb1drn because it is being terminated' (will not retry!)
2020/03/27 21:16:20 Ran for 2h1m58s
error: could not run steps: step integration failed: template pod "integration" failed: pod was deleted while ci-operator step was waiting for it
``` 
looking in to it

**Comment by LalatenduMohanty** [comment]
Another run, but the issue is same

**Comment by LalatenduMohanty** [comment]
@sdodson The e2e tests has passed now, we should remove the hold

**Comment by sdodson** [comment]
> @sdodson The e2e tests has passed now, we should remove the hold
/hold cancel

**Comment by sdodson** [comment]
/hold cancel
No need to block on me if the tests are passing now.

**Pull request merged**
