### PR TITLE
Bug 2006145: install/0000_00_cluster-version-operator_03_deployment: Explicit kube-api-access

### PR DESCRIPTION
**Pull request by wking**
Backporting #660 to 4.9.

### CODE REVIEW

**Comment by sdodson** [comment]
Upstream PR has merged and this is a blocker, so labeling for merge.

**Comment by wking** [comment]
[Sandbox][1] and [replica/not-ready][2] issues are unrelated.

/override ci/prow/e2e-agnostic
/override ci/prow/e2e-agnostic-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/661/pull-ci-openshift-cluster-version-operator-release-4.9-e2e-agnostic-upgrade/1440370289220259840
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/661/pull-ci-openshift-cluster-version-operator-release-4.9-e2e-agnostic/1440370289186705408

**Pull request merged**
