### PR TITLE
OCPBUGS-32678: Fix a panic caused by a data race

### PR DESCRIPTION
**Pull request by Davoska**
After the CVO has started and its worker goroutines are starting to work, a panic may occur due to a data race.

Originally (at 961873d6), the `SyncWorker.Start()` method was exclusively waiting for a signal on the `SyncWorker.notify` channel from the `SyncWorker.Update()` method before attempting the first application of a payload.

After the `Start()` method got the signal, its required values were already initialized by the `SyncWorker.Update()` method, such as the `SyncWorker.work` field.

However, the 9222fa9a introduced another section of the CVO that can signal the `SyncWorker.notify` channel.

The `SyncWorker.NotifyAboutManagedResourceActivity()` method now signals the channel upon an activity on a managed resource. This signal may occur before the `SyncWorker.Update()` has finished. The signal thus starts an attempt of the `SyncWorker.Start()` method to apply a payload before the `SyncWorker.work` field could have been set by the `SyncWorker.Update()` method.

This currently results in an `"invalid memory address or nil pointer dereference"` panic in the `SyncWork.calculateNextFrom()` method because a nil pointer is passed by the `SyncWorker.Start()` method.

This panic can be seen in the following logs [1, 2]. Be sure to notice messages such as `Notify the sync worker: Cluster operator etcd changed Degraded from "False" to "True"` caused by the
`NotifyAboutManagedResourceActivity` method right before a panic occurs.

This PR will fix the issue by introducing a new channel to exclusively signal the start of the initial attempt of the application after the `SyncWorker.Update()` has finished. It may also be used for any consecutive signals to attempt an application. This ensures the `Update()` has finished at least once before we attempt to apply the payload.

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-aws-workers-rhel8/1804819848023248896/artifacts/e2e-aws-workers-rhel8/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-545d8cb5db-v2bf4_cluster-version-operator_previous.log
[2] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.11-e2e-ovirt/1805174927066664960/artifacts/e2e-ovirt/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-849c49896b-wnn8v_cluster-version-operator_previous.log

This pull request references https://issues.redhat.com/browse/OCPBUGS-32678

### CODE REVIEW

**Comment by Davoska** [comment]
After a test for the bug is introduced without its fix:
```shell
$ git checkout 7f9cf621ce33f182319bd57146b45a178a1ed16d
HEAD is now at 7f9cf621 pkg/cvo/sync_worker_test.go: Add test for panic caused by goroutine synchronization
$ go test ./... -count=1
...
I0715 14:42:41.027363  348647 sync_worker.go:565] Start: starting sync worker
I0715 14:42:41.027465  348647 sync_worker.go:584] Notify the sync worker: Cluster operator A changed versions
E0715 14:42:41.028015  348647 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 596 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1c91a20, 0x32c6ed0})
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000693500?})
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1c91a20?, 0x32c6ed0?})
        /home/dhurta/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/openshift/cluster-version-operator/pkg/cvo.(*SyncWork).calculateNextFrom(0xc00083bc20, 0x0)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker.go:730 +0x58
github.com/openshift/cluster-version-operator/pkg/cvo.(*SyncWorker).Start.func1()
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker.go:589 +0x2f2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006a0f68, {0x228dfe0, 0xc0007b4570}, 0x1, 0xc0007be000)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006a0f68, 0x989680, 0x0, 0x1, 0xc0007be000)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
github.com/openshift/cluster-version-operator/pkg/cvo.(*SyncWorker).Start(0xc0007a3088, {0x22ac5e8, 0xc0004b1590}, 0x1)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker.go:569 +0x135
github.com/openshift/cluster-version-operator/pkg/cvo.Test_SyncWorkerShouldNotPanicDueToNotifySignalAtStartUp.func1()
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker_test.go:490 +0x2d
created by github.com/openshift/cluster-version-operator/pkg/cvo.Test_SyncWorkerShouldNotPanicDueToNotifySignalAtStartUp in goroutine 594
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker_test.go:489 +0x12e
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x19e80d8]

goroutine 596 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000693500?})
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x1c91a20?, 0x32c6ed0?})
        /home/dhurta/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.1.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/openshift/cluster-version-operator/pkg/cvo.(*SyncWork).calculateNextFrom(0xc00083bc20, 0x0)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker.go:730 +0x58
github.com/openshift/cluster-version-operator/pkg/cvo.(*SyncWorker).Start.func1()
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker.go:589 +0x2f2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0006a0f68, {0x228dfe0, 0xc0007b4570}, 0x1, 0xc0007be000)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006a0f68, 0x989680, 0x0, 0x1, 0xc0007be000)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:161
github.com/openshift/cluster-version-operator/pkg/cvo.(*SyncWorker).Start(0xc0007a3088, {0x22ac5e8, 0xc0004b1590}, 0x1)
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker.go:569 +0x135
github.com/openshift/cluster-version-operator/pkg/cvo.Test_SyncWorkerShouldNotPanicDueToNotifySignalAtStartUp.func1()
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker_test.go:490 +0x2d
created by github.com/openshift/cluster-version-operator/pkg/cvo.Test_SyncWorkerShouldNotPanicDueToNotifySignalAtStartUp in goroutine 594
        /home/dhurta/work/davoska-cluster-version-operator/cluster-version-operator/pkg/cvo/sync_worker_test.go:489 +0x12e
FAIL    github.com/openshift/cluster-version-operator/pkg/cvo   3.818s
ok      github.com/openshift/cluster-version-operator/pkg/cvo/internal  0.022s
ok      github.com/openshift/cluster-version-operator/pkg/featuregates  4.423s
ok      github.com/openshift/cluster-version-operator/pkg/payload       1.068s
ok      github.com/openshift/cluster-version-operator/pkg/payload/precondition  0.008s
ok      github.com/openshift/cluster-version-operator/pkg/payload/precondition/clusterversion   0.010s
ok      github.com/openshift/cluster-version-operator/pkg/start 0.011s
FAIL
```

After the fix is introduced as well:
```
$ git checkout f5a6202ab90d4c9400cc04eedf75fe810b291068
Previous HEAD position was 7f9cf621 pkg/cvo/sync_worker_test.go: Add test for panic caused by goroutine synchronization
HEAD is now at f5a6202a pkg/cvo/sync_worker.go: Fix panic caused by data race
$ go test ./... -count=1
...
ok      github.com/openshift/cluster-version-operator/pkg/cvo   13.906s
ok      github.com/openshift/cluster-version-operator/pkg/cvo/internal  0.025s
ok      github.com/openshift/cluster-version-operator/pkg/featuregates  4.418s
ok      github.com/openshift/cluster-version-operator/pkg/payload       1.067s
ok      github.com/openshift/cluster-version-operator/pkg/payload/precondition  0.011s
ok      github.com/openshift/cluster-version-operator/pkg/payload/precondition/clusterversion   0.011s
ok      github.com/openshift/cluster-version-operator/pkg/start 0.013s
```

**Comment by Davoska** [comment]
/hold
There is a potential deadlock in the new changes,

**Comment by dis016** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.16-e2e-gcp-ovn-upgrade

**Comment by dis016** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by petr-muller** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade

**Comment by petr-muller** [comment]
/payload-aggregate  periodic-ci-openshift-release-master-ci-4.17-e2e-gcp-ovn-upgrade 10

**Review by petr-muller — APPROVED** [review]
Looks good to me. I am not that happy about increased complexity, but I do not have a good counterproposal.

**Comment by petr-muller** [comment]
I think this can wait for `acknowledge-critical-fixes-only` lift. @Davoska I will leave it up to you whether you want to ask QE to pre-merge test this or not.

**Comment by Davoska** [comment]
Thank you, Petr, for the review. 

This can definitely wait for the `acknowledge-critical-fixes-only` lift :+1: 

Testing this PR is not as easy, unfortunately. The original panic occurred only once in a while, and the new changes are small and technical. The new tests check for the panic that was happening due to the data race. Tests do seem to report that everything is working as expected, but I appreciate any testing I can get, as the worst-case scenario is a potential deadlock.

Hello, @dis016 :wave: What's your take on the PR?

I am not sure what to recommend for testing such a PR. The CI is passing, and the time window to check for the data race in a live cluster is quite small. A static analysis is always appreciated, but I'll leave it up to you.

**Comment by petr-muller** [comment]
My opinion is that because the original panic was very rare,  we do not have a reproducer (and it would be very hard to create one) and you actually added a new unit test that exercises the behavior, additional testing before merge does not bring too much value. Basic scenarios (install, upgrade in different directions, hypershift) are covered by CI. So we likely haven't broken anything obvious, and we do not change any externally observable behaviors that the testing could focus on. That means the remaining factor that we could make worse is overall, large-scale reliability, and that factor is best tested by letting the PR merge so that the code reaches the payload testing battery of jobs.

**Comment by Davoska** [comment]
Well said. I have nothing to add.

/label no-qe

**Pull request merged**
