### PR TITLE
cininnati: fix unknown version fetch

### PR DESCRIPTION
**Pull request by abhinavdahiya**
currently if the current version does not exist in the reponse returned from cincinnati, we use the `0`th node as our version
and return the available updates for that version.
example,

If the response from cincinnati is following:
```console
$ curl --silent --header 'Accept:application/json' https://api.openshift.com/api/upgrades_info/v1/graph | jq .
{
  "nodes": [
    {
      "version": "4.0.0-5",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-5",
      "metadata": {}
    },
    {
      "version": "4.0.0-4",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-4",
      "metadata": {}
    },
    {
      "version": "4.0.0-6",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-6",
      "metadata": {}
    },
    {
      "version": "4.0.0-7",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-7",
      "metadata": {}
    },
    {
      "version": "4.0.0-8",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-8",
      "metadata": {}
    },
    {
      "version": "4.0.0-9",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-9",
      "metadata": {}
    },
    {
      "version": "4.0.0-0.1",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-0.1",
      "metadata": {
        "description": "This is the beta1 image based on the 4.0.0-0.nightly-2019-01-15-010905 build"
      }
    },
    {
      "version": "4.0.0-0.okd-0",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-0.okd-0",
      "metadata": {}
    },
    {
      "version": "4.0.0-0.2",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-0.2",
      "metadata": {}
    },
    {
      "version": "4.0.0-0.3",
      "payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-0.3",
      "metadata": {}
    }
  ],
  "edges": [
    [
      1,
      0
    ],
    [
      0,
      2
    ],
    [
      2,
      3
    ],
    [
      3,
      4
    ],
    [
      4,
      5
    ],
    [
      6,
      8
    ],
    [
      8,
      9
    ]
  ]
}
```

For a cusotm release image generated locally
```console
$ oc get clusterversion -oyaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    creationTimestamp: 2019-02-06T00:51:12Z
    generation: 1
    name: version
    namespace: ""
    resourceVersion: "956"
    selfLink: /apis/config.openshift.io/v1/clusterversions/version
    uid: 4cbc79c7-29a9-11e9-b85c-664f163f5f0f
  spec:
    channel: fast
    clusterID: a7d11204-7193-41ca-ad4a-337a540a5dac
    upstream: https://api.openshift.com/api/upgrades_info/v1/graph
  status:

    availableUpdates:
    - image: quay.io/openshift-release-dev/ocp-release:4.0.0-6
      version: 4.0.0-6

    conditions:
    - lastTransitionTime: 2019-02-06T00:51:21Z
      status: "False"
      type: Available
    - lastTransitionTime: 2019-02-06T00:53:21Z
      status: "False"
      type: Failing
    - lastTransitionTime: 2019-02-06T00:51:21Z
      message: 'Working towards 0.0.1-2019-02-06-003220: 22% complete'
      status: "True"
      type: Progressing
    - lastTransitionTime: 2019-02-06T00:51:21Z
      status: "True"
      type: RetrievedUpdates
    desired:
      image: quay.io/abhinavdahiya/origin-release@sha256:4e9f3686380d26566e9112fdd53262068004a22a85f93111a0f10d0b3dfdc3a9
      version: 0.0.1-2019-02-06-003220
    history:
    - completionTime: null
      image: quay.io/abhinavdahiya/origin-release@sha256:4e9f3686380d26566e9112fdd53262068004a22a85f93111a0f10d0b3dfdc3a9
      startedTime: 2019-02-06T00:51:21Z
      state: Partial
      version: 0.0.1-2019-02-06-003220
    observedGeneration: 1
    versionHash: G0evldCtMHI=
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
The current version is `0.0.1-2019-02-06-003220` and since this is version is not present in the response from cincinnati with use the `0`th node ie `4.0.0-5` and returns available update to `4.0.0-6`

This returns error when current version is not found in response from cincinnati.

/cc @crawford @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Lgtm, might be good to add a test to cvo_test (which should have a table driven test for available update computation)

**Comment by abhinavdahiya** [comment]
@smarterclayton @crawford with https://github.com/openshift/cluster-version-operator/commit/5e34549e94f5d7d8deeaaf7cd8f23b08652e65df -> https://github.com/openshift/cluster-version-operator/commit/4454e8d33795dd4929a72a1da091837b1a989984

added unit test for `GetUpdates`.

**Pull request merged**
