### PR TITLE
Bug 2030628: [release-4.7] Respect noProxy

### PR DESCRIPTION
**Pull request by palonsoro**
PR to backport #622 to release-4.7. It consists of:
- Cherry-picking da19127
- Vendoring golang.org/x/net/http/httpproxy
- Also cherry-picking 91794f0 and ee66c8a in order to backport some fixes made to CVO scenarios tests. The failures fixed at those commits seemed to impact the CVO scenarios test once da19127 was backported and httpproxy was vendored.

### CODE REVIEW

**Review by LalatenduMohanty — APPROVED** [review]

**Comment by palonsoro** [comment]
Hi.

Can this PR be reviewed and merged? Is anything else pending to do so?

**Review by wking — APPROVED** [review]
```console
$ cherry-pick-diff origin/release-4.7..origin/pr/711 origin/release-4.8
ee66c8a2 -> 18d5957d Fixed the cluster version update verify function
91794f06 -> bcf18a02 Fixed fake client for CVO scenarios test
cdca0adc -> c75e3279 vendor: Include golang.org/x/net/http/httpproxy
da191270 -> a114d6d6 pkg/cvo: Respect noProxy

...just context changes for the three non-vendor picks, and then a bunch of divergence on the httpproxy bump...
```

which is a clean enough set of backports for me.  All four commits are part of #691.

/lgtm

**Pull request merged**
