### PR TITLE
NO-JIRA: Simplify unit test TestCVO_UpgradeVerifiedPayload

### PR DESCRIPTION
**Pull request by hongkailiu**
Follow up https://github.com/openshift/cluster-version-operator/pull/1081#discussion_r1763025442 and https://github.com/openshift/cluster-version-operator/pull/1081#discussion_r1763031370

### CODE REVIEW

**Comment by Davoska** [comment]
/retitle NO-JIRA: Simplify unit test TestCVO_UpgradeVerifiedPayload

To get the required `jira/valid-reference` label.

**Comment by Davoska** [comment]
/approve
I'll leave a chance for other contributors to give feedback in case I misunderstood the unit test.

**Review by petr-muller — APPROVED** [review]
/label no-qe
/lgtm
/approve
/meow

**Pull request merged**
