### PR TITLE
vendor: bump openshift/api to pick up Insights capability

### PR DESCRIPTION
**Pull request by rluders**
Vendor bump after adding `Insights` as a capability to [openshift/api](https://github.com/openshift/api/pull/1212).

```bash
$ go get github.com/openshift/api@dc2694e95008443da2f0fb2a3d2f7a552824c79d
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```

using:

```bash
$ go version
go version go1.17.13 linux/amd64
```

> Used steps as [in this PR](https://github.com/openshift/cluster-version-operator/pull/737)

### CODE REVIEW

**Comment by jhadvig** [comment]
Just FYI, this PR is picking up the Console capability

**Comment by creydr** [comment]
@rluders fyi: in #817 I revendored openshift/api too (with more recent changes). I fixed the unit test failures and coauthored you (I hope this is ok)

**Pull request closed without merging**
