### PR TITLE
docs: add checkpointer operator run level

### PR DESCRIPTION
**Pull request by rphillips**
Reserves 05 for the checkpointer run level.

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Why is does cehckpointer need that run level before network and api ?

**Comment by rphillips** [comment]
We would want the checkpointer to run at the earliest point so that it can checkpoint critical services (checkpointer, api-server, controller-manager, and scheduler) in case there is a failure on the node during the rest of the bringup.

**Comment by abhinavdahiya** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
lgtm

**Comment by abhinavdahiya** [comment]
```console
NAME                          STATUS    ROLES     AGE       VERSION
ip-10-0-28-100.ec2.internal   Ready     master    10m       v1.11.0+d4cacc0
ip-10-0-46-25.ec2.internal    Ready     master    10m       v1.11.0+d4cacc0
ip-10-0-5-55.ec2.internal     Ready     master    10m       v1.11.0+d4cacc0
API at https://ci-op-fkqnyij6-928f7-api.origin-ci-int-aws.dev.rhcloud.com:6443 has responded
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
router    1         1         1            0           4m
Found router in openshift-ingress
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
error deploy/router did not come up
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
error deploy/router did not come up
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
error deploy/router did not come up
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
error deploy/router did not come up
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
error deploy/router did not come up
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
error deploy/router did not come up
error: timed out waiting for the condition
error deploy/router did not come up
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
error deploy/router did not come up
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
error deploy/router did not come up
error: .status.conditions accessor error: Failure is of the type string, expected map[string]interface{}
timeout waiting for router to be available
```

Seeing this flake a lot more now.

/retest

**Pull request merged**
