### PR TITLE
Revert #303 and #279

### PR DESCRIPTION
**Pull request by sdodson**
Reverts #303 then #279 
Supersedes #304

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
There is also https://github.com/openshift/cluster-version-operator/pull/304

**Comment by smarterclayton** [comment]
I would prefer #306

**Comment by smarterclayton** [comment]
Going to give 306 a chance, otherwise will revert.

**Comment by smarterclayton** [comment]
/close

in favor of #307 if we need it

**Pull request closed without merging**
