### PR TITLE
Bug 1881514: Prevent hotlooping in ImageStreams

### PR DESCRIPTION
**Pull request by vrutkovs**
`EnsureImagestreamv1` would verify that lookupPolicy and required tags are set. Tags should have matching `importPolicy` and `from` set (other fields are set by controller)

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold
Added logging commit to ensure we no longer hotloop

**Comment by vrutkovs** [comment]
```
$ curl -Ls https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/579/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic/1399351863404400640/artifacts/e2e-agnostic/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-578f5d68d7-mpg4q_cluster-version-operator.log | grep -I "Updating imagestream" | wc -l
0
```
No longer hotlooping on those

**Comment by wking** [comment]
[API connectivity][1] is unrelated.

/override ci/prow/e2e-agnostic-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/579/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1399638849889505280

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
API connectivity is [still][1] unrelated.

/override ci/prow/e2e-agnostic-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/579/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1399801282042007552

**Pull request merged**
