### PR TITLE
OWNERS: Add component Cluster Version Operator

### PR DESCRIPTION
**Pull request by sdodson**
/cc @wking @abhinavdahiya

### CODE REVIEW

**Comment by wking** [comment]
What is this about?  I don't see anything about `component` in [the upstream docs][1] linked from the file header.

[1]: https://git.k8s.io/community/contributors/guide/owners.md

**Comment by sdodson** [comment]
> What is this about? I don't see anything about `component` in [the upstream docs](https://git.k8s.io/community/contributors/guide/owners.md) linked from the file header.

It's used downstream to facilitate mapping to BZ Components.

**Pull request merged**
