### PR TITLE
Revert "Merge pull request #279 from smarterclayton/config_map"

### PR DESCRIPTION
**Pull request by deads2k**
This reverts commit 27c4671aa0cbfbbf20324cf06145b44ec2bca45e, reversing
changes made to b89aa75004e83f49002250917bcfac82eb17bd05.

reverts https://github.com/openshift/cluster-version-operator/pull/279 in case it's causing the CI issues.

### CODE REVIEW

**Comment by smarterclayton** [comment]
If this passes revert is fine.

**Comment by deads2k** [comment]
/hold

if the merged fix works, then this is unnecessary.

**Comment by smarterclayton** [comment]
close in favor of #307 if we need it

**Pull request closed without merging**
