### PR TITLE
Bug 1841239: Avoid pre-creating clusteroperators that should be excluded

### PR DESCRIPTION
**Pull request by csrwng**
Backport of https://github.com/openshift/cluster-version-operator/pull/370

### CODE REVIEW

**Comment by wking** [comment]
/lgtm

Looks like a clean backport to me.  Was there a reason you didn't comment with `/cherrypick release-4.4` in #370 and let the bot handle the backport bug and PR for you?

**Comment by wking** [comment]
/hold

Unifying with #348 per [this comment][1] makes sense to me.

[1]: https://github.com/openshift/cluster-version-operator/pull/348#issuecomment-635502701

**Comment by csrwng** [comment]
> Looks like a clean backport to me. Was there a reason you didn't comment with `/cherrypick release-4.4` in #370 and let the bot handle the backport bug and PR for you?

Premature optimization :) I thought the patch wouldn't apply cleanly. 



> Unifying with #348 per [this comment](https://github.com/openshift/cluster-version-operator/pull/348#issuecomment-635502701) makes sense to me.

agree

**Comment by jottofar** [comment]
Unifying with #348 per [this comment](https://github.com/openshift/cluster-version-operator/pull/348#issuecomment-635502701) makes sense to me as well.

**Comment by csrwng** [comment]
@wking @jottofar now included the #348 commit in this one (have no idea how to change a cherry-pick PR)

**Comment by wking** [comment]
Hrm, #348 never had a backing bug.  Which probably means we need to grow the QE verification scope on *this* series' 4.5 bug so they confirm that functionality is working as expected too.  Or are we just going to assume "create ClusterOperators early" works and not cover it in QE for 4.5 or 4.4?

Also, I'm not sure why [the update job][1] failed.  Is there a list of failing vs. flaky/optional failures in the build log that I'm just missing?

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/376/pull-ci-openshift-cluster-version-operator-release-4.4-e2e-aws-upgrade/21

**Comment by csrwng** [comment]
> Or are we just going to assume "create ClusterOperators early" works and not cover it in QE for 4.5 or 4.4?

I think the right thing to do is to make the bug about introducing the "create clusteroperators early" functionality in 4.4. The other part is just a corollary fix so that it works properly for ROKS as well. Not sure how that works as far as depencies go though. There was no BZ to introduce the function in 4.5, but I think the 4.4 bug requires a 4.5 bug to exist.

**Comment by csrwng** [comment]
```
[It] [Top Level] [Feature:Platform] ClusterOperators should define at least one namespace in their lists of related objects [Suite:openshift/conformance/parallel]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/operators/clusteroperators.go:54
May 28 22:12:28.385: INFO: Running AfterSuite actions on all nodes
May 28 22:12:28.385: INFO: Running AfterSuite actions on node 1
fail [github.com/openshift/origin/test/extended/operators/clusteroperators.go:57]: ClusterOperator: machine-config
```
Looks like this is missing a backport of https://github.com/openshift/machine-config-operator/pull/1566

**Comment by sdodson** [comment]
Just posted a quick note to bug 1841239, QE still has to verify the 4.5 bug anyway and I'm sure once they do that they'll understand everything that's going on in this PR and the linked bug.

**Comment by sdodson** [comment]
> Looks like this is missing a backport of [openshift/machine-config-operator#1566](https://github.com/openshift/machine-config-operator/pull/1566)

Hmm, starting to think we should call in @deads2k to round up all the follow up work that should come along with backporting the CVO pre-fill? This is just docs but it's linked from the original PR too https://github.com/openshift/cluster-version-operator/pull/363

**Comment by deads2k** [comment]
looks faithful.  I don't feel strongly about a readme

/lgtm

**Comment by deads2k** [comment]
/hold

hold for https://github.com/openshift/machine-config-operator/pull/1764

**Comment by wking** [comment]
We still have [no feature-request bug][1] to hang this backport on though, right?  I don't think we should pull this back to 4.4 hung on a bug about how the initial 4.5 feature (which landed without a bug) was fixed for ROKS.  4.4 isn't broken at all on ROKS without this PR, and will still not be broken once we land this PR.  Can we grow a new series about pre-created cluster-operators, so QE can verify that that is working for 4.5, and then hang this PR on a 4.4 backport of that one?

**Comment by sdodson** [comment]
> We still have [no feature-request bug](https://github.com/openshift/enhancements/pull/149#issuecomment-635742243) to hang this backport on though, right? I don't think we should pull this back to 4.4 hung on a bug about how the initial 4.5 feature (which landed without a bug) was fixed for ROKS. 4.4 isn't broken at all on ROKS without this PR, and will still not be broken once we land this PR. Can we grow a new series about pre-created cluster-operators, so QE can verify that that is working for 4.5, and then hang this PR on a 4.4 backport of that one?

We've provided QE notes in the bug that I believe explain the situation sufficiently. If they have questions I expect them to ask.

**Comment by wking** [comment]
/hold

```
Building github.com/openshift/cluster-version-operator (v1.0.0-204-gc1c8d84d-dirty)
# github.com/openshift/cluster-version-operator/pkg/cvo
pkg/cvo/sync_worker.go:621:8: undefined: contextIsCancelled
pkg/cvo/sync_worker.go:622:15: cr.CancelError undefined (type *consistentReporter has no field or method CancelError)
```

[1]: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/376/pull-ci-openshift-cluster-version-operator-release-4.4-e2e-aws/1277253932929781760

**Comment by csrwng** [comment]
rebased, fixed

**Pull request merged**
