### PR TITLE
OCPVE-673: Bump API to Add OLM Capability

### PR DESCRIPTION
**Pull request by eggfoobar**
Bump API  to add OLM capability

- bumped to 1.28
- updated leader lock to use new LeasesResourceLock
- updated unit tests to account for new capability

/hold

Holding until API change is merged in https://github.com/openshift/api/pull/1589

### CODE REVIEW

**Comment by eggfoobar** [comment]
/unhold

API change was merged in

**Comment by eggfoobar** [comment]
/unhold

The addition in CVO was validated to work with ClusterBot, after we had resolved some image-registry errors, the pipeline now looks better. However, because of the addition of `Build` as optional to the API yesterday https://github.com/openshift/api/pull/1618 some other tests started breaking, but regarding the purpose of this PR the OLM 
tests are correctly being skipped or handled.

I'll unblock openshift/origin#28302 since the CI for no-cap runs weekly, that change should get in before the CI runs.

Merging this PR, will unblock:
openshift/operator-framework-olm#565
openshift/cluster-monitoring-operator#2105

Ran: `test e2e openshift/operator-framework-olm#565,openshift/cluster-monitoring-operator#2105,openshift/origin#28302,openshift/cluster-version-operator#971 aws,no-capabilities`

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1712923427997749248

**Comment by wking** [comment]
Rolling back capability addition from the ClusterVersion CRD is known to break the ability of the CVO to write the no-longer-recognized capability string to `status`.

/override ci/prow/e2e-agnostic-ovn-upgrade-out-of-change

ClusterBot testing looks good and openshift/origin#28302 has merged.

/lgtm
/approve

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/971/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn-upgrade-out-of-change/1712973235517132800

**Comment by bparees** [comment]
> Rolling back capability addition from the ClusterVersion CRD is known to break the ability of the CVO to write the no-longer-recognized capability string to status.

@wking the next time(if there is a next time) we run into that i think we will drop the status validation, even if only temporarily, wdyt?

**Comment by wking** [comment]
what does "if only temporarily" mean?  Do we bump the API repo, vendor bump here, and try and remember to vendor-bump again with enum re-tightening once we get past branch-fork?  Or can we just drop the `status` enums altogether?

**Comment by bparees** [comment]
> what does "if only temporarily" mean? Do we bump the API repo, vendor bump here, and try and remember to vendor-bump again with enum re-tightening once we get past branch-fork

we wouldn't need to get past branch fork, just until we have a nightly that doesn't include the reverted cap name so upgrades don't fail, right?

but yes, more or less that's what temporarily would mean.  and with "if only temporarily" i was trying to convey "at that point we'd decide if we wanted to only do it temporarily, or convince ourselves to drop them permanently"

**Comment by wking** [comment]
I've opened openshift/api#1624 floating "drop the enum from `status.capabilities`.

**Pull request merged**
