### PR TITLE
Bug 1825396: upgrades with force should set verified to false

### PR DESCRIPTION
**Pull request by jottofar**

### CODE REVIEW

**Comment by jottofar** [comment]
/hold
See discussion in https://bugzilla.redhat.com/show_bug.cgi?id=1825396#c6 as to final bug resolution.

**Comment by wking** [comment]
/retest

I'm curious about what happens to no-longer defined jobs like e2e-aws.

**Comment by jottofar** [comment]
/close

Bug closed with a doc update.

**Pull request closed without merging**
