### PR TITLE
Bug 2009845: pkg/cvo/sync_worker: Log transition to updating

### PR DESCRIPTION
**Pull request by wking**
To make it easier to understand why this is happening.

### CODE REVIEW

**Comment by vrutkovs** [comment]
I don't see this log line during e2e-agnostic-update - do we expect this to show up during standard update?

**Comment by wking** [comment]
We do expect it during updates, but only from the pod that notices the transition to updating.  That pod will bump the CVO Deployment to pull in a new CVO, and when that CVO comes up, it should go straight into updating [over here][1].  [The most recent update presumit][2] failed to install, but [the previous round][3] had:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/730/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1486127605978501120/artifacts/e2e-agnostic-upgrade/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-56487994b8-zc2n8_cluster-version-operator.log | grep 'ClusterVersionOperator\|Propagating initial target version\|Work changed\|Detected while\|Running sync.*in state' | head
I0126 01:46:07.179253       1 start.go:23] ClusterVersionOperator v1.0.0-754-g368ad0ef-dirty
I0126 01:46:08.502441       1 cvo.go:338] Starting ClusterVersionOperator with minimum reconcile period 2m8.765337491s
I0126 01:46:08.603980       1 sync_worker.go:255] Propagating initial target version { registry.build02.ci.openshift.org/ci-op-c5hfgrlk/release@sha256:bbfcf15fe6e61a4eaca0e38472506e7e119a785df88f6de56ede59ecbdbf585a true} to sync worker loop in state Updating.
I0126 01:46:08.604759       1 sync_worker.go:511] Detected while calculating next work: version change (from {  false} to { registry.build02.ci.openshift.org/ci-op-c5hfgrlk/release@sha256:bbfcf15fe6e61a4eaca0e38472506e7e119a785df88f6de56ede59ecbdbf585a true})
I0126 01:46:08.604840       1 sync_worker.go:559] Running sync registry.build02.ci.openshift.org/ci-op-c5hfgrlk/release@sha256:bbfcf15fe6e61a4eaca0e38472506e7e119a785df88f6de56ede59ecbdbf585a (force=true) on generation 3 in state Updating at attempt 0
I0126 01:50:45.183322       1 sync_worker.go:559] Running sync registry.build02.ci.openshift.org/ci-op-c5hfgrlk/release@sha256:bbfcf15fe6e61a4eaca0e38472506e7e119a785df88f6de56ede59ecbdbf585a (force=true) on generation 3 in state Updating at attempt 1
I0126 01:56:27.608973       1 sync_worker.go:559] Running sync registry.build02.ci.openshift.org/ci-op-c5hfgrlk/release@sha256:bbfcf15fe6e61a4eaca0e38472506e7e119a785df88f6de56ede59ecbdbf585a (force=true) on generation 3 in state Reconciling at attempt 0
```

We should be able to access the outgoing, change-noticing pod in Loki, but our update CI is dev-tips -> dev-tips + PR, so the outgoing CVO here lacks the logging code I'm trying to add.

[1]: https://github.com/openshift/cluster-version-operator/blob/037f19868ebf6205172d84135e35137e78970a5f/pkg/cvo/cvo.go#L572-L573
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/730/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1486379455143219200
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/730/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1486127605978501120

**Comment by vrutkovs** [comment]
>We should be able to access the outgoing, change-noticing pod in Loki, but our update CI is dev-tips -> dev-tips + PR, so the outgoing CVO here lacks the logging code I'm trying to add.

Lets see if [test upgrade https://github.com/openshift/cluster-version-operator/pull/730 4.11](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1486632150777204736) would work

**Comment by vrutkovs** [comment]
>Work changed, transitioning from Reconciling and the suggested incoming Updating state to Updating

A bit odd, but I guess it could be reworded later

iiuc after update is done it would change Updating -> Reconciling, right?

**Comment by wking** [comment]
> A bit odd, but I guess it could be reworded later

Yeah.  I'm only logging both current and suggested incoming while we debug the `Initializing` -> `Updating` transition, then we can rip this back out.  Although I'm fine if it ships with 4.10 production releases without getting reverted.

> iiuc after update is done it would change Updating -> Reconciling, right?

Yeah, but that happens in [yet another location][1], which is not currently instrumented with logging.  But it will have an empty `Result of work...`, and the next round willl get a `Running sync ... in state Reconciling ...`, so I don't think it needs additional logging unless we have specific concerns that need debugging.

[1]: https://github.com/openshift/cluster-version-operator/blob/404b1970876b64f7adec4e38710c69594e42e317/pkg/cvo/sync_worker.go#L381

**Comment by wking** [comment]
[this][1] was an unrelated PDB issue; I don't think we need to wait out a retest.

/override ci/prow/e2e-agnostic-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/730/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1486520630915371008

**Pull request merged**
