### PR TITLE
Revert "METAL-1053, OCPBUGS-33983: Remove baremetal dependency on MachineAPI capability"

### PR DESCRIPTION
**Pull request by damdo**
Reverts openshift/cluster-version-operator#1051

### CODE REVIEW

**Comment by damdo** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.17-e2e-aws-ovn-techpreview

**Comment by petr-muller** [comment]
Also note https://github.com/openshift/cluster-version-operator/pull/1062 - I'll run the payload job there too, maybe that's the problem

**Comment by neisw** [comment]
/override ci/prow/e2e-hypershift-conformance 

broken due to [OCPBUGS-36299](https://issues.redhat.com/browse/OCPBUGS-36299)

**Pull request merged**
