### PR TITLE
Bumping the GOLANGCI_LINT_VERSION to v1.43.0

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Comment by LalatenduMohanty** [comment]
/override ci/prow/e2e-agnostic-upgrade 

As the change does not impact CVO runtime

**Comment by wking** [comment]
[Six seconds of Kube-API-server disruption][1] are not related to the linter bump ;).

/override ci/prow/e2e-agnostic-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/695/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1463324192467324928

**Pull request merged**
