### PR TITLE
[CNF-5646] bump api version to add new capability

### PR DESCRIPTION
**Pull request by qJkee**
bump openshift/api with new capability

### CODE REVIEW

**Comment by wking** [comment]
[upgrade-out-of-change][1] CI will never complete when dropping a cap from the CRD enum.  That run got far enough to be running the target CVO, which is good enough for these changes.

/override ci/prow/e2e-agnostic-upgrade-out-of-change

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/835/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade-out-of-change/1569434175847534592

**Comment by wking** [comment]
Will need a rebase around the vendor bumps that just landed in #833.

**Comment by wking** [comment]
Also, before we land this, can we remove the draft status from openshift/cluster-csi-snapshot-controller-operator#126 to confirm that the pull request presubmits all pass with the annotated manifests removed?  That's covered in step 3 of [the onboarding docs][1], and helps protect against "oops, I guess CI fails with this capability removed, and we need to..." excitement before we commit to landing hard-to-revert changes in multiple repositories.

[1]: https://github.com/openshift/enhancements/blob/4290d908b82fcf2cfaf692bdaf913530f552fa9c/enhancements/installer/component-selection.md#how-to-implement-a-new-capability

**Comment by gnufied** [comment]
@qJkee can you update this bump again and pull from latest `api` and `client-go` repos?  I have updated `ClusterCSIDriver` objects with new functionality and hence need the CVO to apply latest CRDs. 

xref - https://github.com/openshift/api/pull/1271

**Comment by qJkee** [comment]
@gnufied 
Yes, will do

**Comment by qJkee** [comment]
@wking 
Does 2e-agnostic-upgrade-out-of-change still not working properly?

**Comment by wking** [comment]
[e2e-agnostic-upgrade-out-of-change][1] goes from your proposed state to the current base branch, so it drops a cap.  That will always fail on:

````console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/835/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade-out-of-change/1572284562753458176/artifacts/e2e-agnostic-upgrade-out-of-change/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-75f44b9fbb-gqx56_cluster-version-operator.log | grep 'ClusterVersion.config.openshift.io .* is invalid' | tail -n1
I0920 21:50:51.604571       1 cvo.go:550] Error handling openshift-cluster-version/version: ClusterVersion.config.openshift.io "version" is invalid: status.capabilities.enabledCapabilities[0]: Unsupported value: "CSISnapshot": supported values: "openshift-samples", "baremetal", "marketplace", "Console", "Insights", "Storage"
```

as the CVO tries to explain that `CSISnapshot` is enabled to an API-server that is looking at a CRD which no longer mentions `CSISnapshot`.  The fact that the job got far enough to roll out the base-branch CRD and CVO is sufficient for this PR, and we can `/override ...` when we're ready to land.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/835/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade-out-of-change/1572284562753458176

**Review by wking — APPROVED** [review]
[OCPBUGS-1904][1] isn't fixed yet.  Dropping a cap from that validation enum breaks updates, but, but the bug is a 4.12 blocker now, which means we're committed to making this work, and won't have to revert the `CSISnapshot` enum entry.

/lgtm

[1]: https://issues.redhat.com/browse/OCPBUGS-1904

**Review by wking — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
This will never pass for cap addition; overriding again:

/override e2e-agnostic-upgrade-out-of-change

**Comment by qJkee** [comment]
> This will never pass for cap addition; overriding again:
> 
> /override e2e-agnostic-upgrade-out-of-change

ahh, I did not mention that. I thought it was another "good" job that started to fail, thank you!

**Comment by qJkee** [comment]
since Trevor already done that, overriding the test
/override ci/prow/e2e-agnostic-upgrade-out-of-change

**Comment by wking** [comment]
[Network-y `TargetDown` and OAuth connectivity][1] are orthogonal.

/override ci/prow/e2e-agnostic-upgrade-into-change

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/835/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade-into-change/1579546099574640640

**Review by wking — APPROVED** [review]
/lgtm
/override ci/prow/e2e-agnostic-upgrade-out-of-change

**Pull request merged**
