### PR TITLE
[PSAP-741] vendor: update openshift/api for NodeTuning capability

### PR DESCRIPTION
**Pull request by dagrayvid**
This PR updates the openshift/api dependency version to bring in the new NodeTuning capability, and updates the unit tests to include this capability.

See [PSAP-741](https://issues.redhat.com/browse/PSAP-741) as well as the merged PR https://github.com/openshift/api/pull/1373.

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold

This is suspicious and should be investigated. The `e2e-agnostic-upgrade-out-of-change` job fails consistently (all four runs here) on the following. This does not happen on other PRs so it's somehow likely it's really caused by the change.

```
{Cluster did not complete upgrade: timed out waiting for the condition: Working towards 4.13.0-0.ci.test-2023-01-09-214219-ci-op-xsft9vl1-initial: 4 of 831 done (0% complete)  }
```

**Comment by petr-muller** [comment]
From CVO log:

```
I0111 18:40:47.628727       1 cvo.go:550] Error handling openshift-cluster-version/version: ClusterVersion.config.openshift.io "version" is invalid: status.capabilities.enabledCapabilities[3]: Unsupported value: "NodeTuning": supported values: "openshift-samples", "baremetal", "marketplace", "Console", "Insights", "Storage", "CSISnapshot"
```

**Comment by dagrayvid** [comment]
Thanks @petr-muller for digging into that. Looking at past PRs for capability addition, it seems like [this will never pass.](https://github.com/openshift/cluster-version-operator/pull/835#issuecomment-1273613274)
cc @wking

**Comment by petr-muller** [comment]
Yeah that actually sounds plausible. We cannot upgrade from the CVO with the cap to CVO without it. Hopefully Trevor will confirm.

**Comment by wking** [comment]
I rounded with @dagrayvid out of band.  Summarizing:

* [These docs][1] cover the intended new-capability onboarding flow.
* This pull request is step 5.
* Opening openshift/cluster-node-tuning-operator#524 is step 2.
* David's confirmed that openshift/cluster-node-tuning-operator#524 shows all the NTO bits removed, with no dangling resources (3.i).
* For component-is-not-installed CI (3.ii), [this e2e-aws-ovn][2] run on openshift/cluster-node-tuning-operator#524 shows `oc explain should contain proper spec+status for CRDs` failing on `the server doesn't have a resource type "profiles"`.  David will open an origin pull request touching [here][3] or similar to avoid that issue.  Depending on how touchy we feel the pull request is, we could:
    * Test the union of this pull request, openshift/cluster-node-tuning-operator#524, and the origin pull-request in no-caps cluster-bot to confirm the setup is happy.  Or...
    * Skip pre-testing, just merge this pull request and the origin one, and check [the no-caps periodic][4] to see if we need any additional tweaks (also, the no-caps periodic seems sad in 4.13 at the moment, but I'll dig into that separately).
    
And yes, once we are ready to go-ahead with this pull request, we can override upgrade-out-of-change, because adding a new cap is expected to be a one-way gate.

[1]: https://github.com/openshift/enhancements/blob/5c92a52b27580c96eaf7ea3af79fef35463b3e2a/enhancements/installer/component-selection.md#how-to-implement-a-new-capability
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-node-tuning-operator/524/pull-ci-openshift-cluster-node-tuning-operator-master-e2e-aws-ovn/1603285604148187136
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-node-tuning-operator/524/pull-ci-openshift-cluster-node-tuning-operator-master-e2e-aws-ovn/1603285604148187136
[4]: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.13-informing#periodic-ci-openshift-release-master-ci-4.13-e2e-aws-sdn-no-capabilities

**Comment by dagrayvid** [comment]
/retest

Now that the [openshift/origin#27657](https://github.com/openshift/origin/pull/27657) has merged

**Comment by dagrayvid** [comment]
@wking, the e2e-aws-ovn test in on https://github.com/openshift/cluster-node-tuning-operator/pull/524 is now passing, since we merged https://github.com/openshift/origin/pull/27657. 

Is there anything else we should be looking out for from the no-capabilities periodic, before merging this PR?

**Comment by dagrayvid** [comment]
@petr-muller can you take another look at this PR now?

**Comment by dagrayvid** [comment]
@LalatenduMohanty @wking @petr-muller I believe this PR is ready to merge, PTAL.

**Review by wking — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
This test will never pass on capability-bumps, because the CVO wants to implicitly enable the rollback-removed capability, but the cap is no longer  part of the CRD enum:

/override ci/prow/e2e-agnostic-upgrade-out-of-change

**Pull request merged**
