### PR TITLE
OCPBUGS-20762: [4.14] Bump http-related deps

### PR DESCRIPTION
**Pull request by petr-muller**
Created with:

```console
$ go get golang.org/x/net@v0.17.0
$ go get k8s.io/apimachinery@v0.27.7
$ go get k8s.io/apiserver@v0.27.7
$ go get github.com/openshift/library-go@release-4.14
$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Comment by jiajliu** [comment]
regression test against the pr pass.
/label qe-approved

**Comment by sdodson** [comment]
Still needs lgtm and backport-risk-assessed

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request merged**
