### PR TITLE
docs/dev/operators: Document ComponentOverride injection

### PR DESCRIPTION
**Pull request by wking**
To help devs to test one-off object changes.

Builds on #59; review that first.

CC @abhinavdahiya, @runcom

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
Can you drop #59 changes. They don't seem related

**Comment by wking** [comment]
Ok, I've pushed 636905e -> 98e1d72, addressing all of your review (I think ;), except for [the `jq` vs. JSONPath one][1].  More on why I'm using `jq` [here][2].  I'm happy to switch to JSONPath if there's a way to get it to spit out JSON objects.  And I'll grudgingly switch to JSONPath in the absence of JSON-object output if you really don't want to involve `jq`.  Thoughts?

[1]: https://github.com/openshift/cluster-version-operator/commit/636905e14d256dd50b88966e6a468278f8e177b0#r31563572
[2]: https://github.com/openshift/cluster-version-operator/commit/636905e14d256dd50b88966e6a468278f8e177b0#commitcomment-31634117

**Comment by wking** [comment]
Oops, I just pushed 98e1d72 -> f83e20b adding notes about disabling the CVO completely.  @abhinavdahiya, can you take another look and maybe re-`/lgtm`?

**Pull request merged**
