### PR TITLE
update library-go to pick up feature-set annotation change

### PR DESCRIPTION
**Pull request by deads2k**
bring in https://github.com/openshift/library-go/pull/1408

### CODE REVIEW

**Review by petr-muller — APPROVED** [review]

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by petr-muller** [comment]
/test e2e-agnostic-upgrade-out-of-change

```
Nov 10 00:01:22.181: Unexpected alerts fired or pending during the upgrade:
alert OVNKubernetesNorthboundDatabaseInboundConnectionMissing fired for 30 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
alert OVNKubernetesNorthboundDatabaseOutboundConnectionMissing fired for 30 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
alert OVNKubernetesSouthboundDatabaseInboundConnectionMissing fired for 30 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
alert OVNKubernetesSouthboundDatabaseOutboundConnectionMissing fired for 30 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
```

**Comment by petr-muller** [comment]
/retest

Hm, similar thing:
```
alert OVNKubernetesNorthboundDatabaseClusterMemberError fired for 60 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
alert OVNKubernetesNorthboundDatabaseInboundConnectionMissing fired for 60 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
alert OVNKubernetesNorthboundDatabaseOutboundConnectionMissing fired for 60 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
alert OVNKubernetesSouthboundDatabaseClusterMemberError fired for 60 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
alert OVNKubernetesSouthboundDatabaseInboundConnectionMissing fired for 60 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
alert OVNKubernetesSouthboundDatabaseOutboundConnectionMissing fired for 60 seconds with labels: {namespace="openshift-ovn-kubernetes", severity="warning"}
```

**Pull request merged**
