### PR TITLE
vendor: update openshift/api

### PR DESCRIPTION
**Pull request by honza**
To bring in new capabilities

### CODE REVIEW

**Comment by wking** [comment]
/hold

[Unit tests][1] say we have to make a few updates:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/751/pull-ci-openshift-cluster-version-operator-master-unit/1504530164090933248/build-log.txt | grep '_test.go.*unexpected'
    cvo_scenarios_test.go:194: unexpected object:   &v1.ClusterVersion{
    cvo_scenarios_test.go:592: unexpected object:   &v1.ClusterVersion{
    cvo_scenarios_test.go:963: unexpected object:   &v1.ClusterVersion{
    cvo_scenarios_test.go:3145: unexpected status item 0
    cvo_scenarios_test.go:3145: unexpected status item 0
    cvo_scenarios_test.go:3145: unexpected status item 0
    cvo_scenarios_test.go:2202: unexpected object:   &v1.ClusterVersion{
    cvo_scenarios_test.go:3145: unexpected status item 2
    cvo_scenarios_test.go:3145: unexpected status item 0
    cvo_scenarios_test.go:2926: unexpected status: {1 <nil> 0 3 0 false true Gyh2W6qcDO4= 0001-01-01 00:00:00 +0000 UTC {1.0.0-abc image/image:1  []} false {PayloadLoaded Payload loaded version="1.0.0-abc" image="image/image:1" <nil> {1.0.0-abc image/image:1  []} false {13872492981397244319 39718236 0x2c99fa0}} {[openshift-samples baremetal] [openshift-samples baremetal]}}
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/751/pull-ci-openshift-cluster-version-operator-master-unit/1504530164090933248#1:build-log.txt%3A61

**Comment by honza** [comment]
Interesting. Unit tests fail in CI, on my lab host, but not on my laptop?

**Comment by honza** [comment]
Depends on #752

**Comment by wking** [comment]
#752 has landed.

/test unit

**Comment by wking** [comment]
[`does not support zone 1 in location westus`][1] is [rhbz#2060687][2], but we know this works from [the e2e-operator run][3], so:

/override ci/prow/e2e-agnostic

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/751/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic/1504564938671132672#1:build-log.txt%3A52
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2060687
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/751/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-operator/1504564938708881408

**Comment by wking** [comment]
/hold cancel
/lgtm

Looked good before the rebase, and now [passes unit tests][1].

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/751/pull-ci-openshift-cluster-version-operator-master-unit/1504588853640433664

**Comment by wking** [comment]
[Prometheus 503][1] is unrelated:

/override ci/prow/e2e-agnostic-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/751/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1504588853493633024

**Pull request merged**
