### PR TITLE
Bug 1947797: Bumping openshift/api to vendor apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
```
$ go mod tidy
go: finding module for package k8s.io/api/discovery/v1alpha1
go: finding module for package k8s.io/api/batch/v2alpha1
github.com/openshift/cluster-version-operator/pkg/cvo imports
	k8s.io/client-go/kubernetes/scheme imports
	k8s.io/api/batch/v2alpha1: module k8s.io/api@latest found (v0.21.0), but does not contain package k8s.io/api/batch/v2alpha1
github.com/openshift/cluster-version-operator/pkg/cvo imports
	k8s.io/client-go/kubernetes/scheme imports
	k8s.io/api/discovery/v1alpha1: module k8s.io/api@latest found (v0.21.0), but does not contain package k8s.io/api/discovery/v1alpha1
```

**Comment by vrutkovs** [comment]
Seems that needs `go mod vendor`

**Comment by vrutkovs** [comment]
I included the bump in https://github.com/openshift/cluster-version-operator/pull/566 (its necessary there), lets close this PR?

**Comment by LalatenduMohanty** [comment]
> I included the bump in #566 (its necessary there), lets close this PR?

The changes looks different in your PR. I wanted to get this in to CVO which has my recent changes in  https://github.com/openshift/api/pull/921 .

**Comment by LalatenduMohanty** [comment]
Never mind , you have the required changes in https://github.com/openshift/cluster-version-operator/pull/566/commits/725d4f879aa08fe3b47e4b2c8aa487cf28d49dea

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
/hold

```
INFO[2021-05-20T08:26:16Z] error: failed creating CRD clusterversions.config.openshift.io: CustomResourceDefinition.apiextensions.k8s.io "clusterversions.config.openshift.io" is invalid: [spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1", Served:true, Storage:true, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(0xc0484a4218), Subresources:(*apiextensions.CustomResourceSubresources)(0xc0102cd980), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition{apiextensions.CustomResourceColumnDefinition{Name:"Version", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.history[?(@.state==\"Completed\")].version"}, apiextensions.CustomResourceColumnDefinition{Name:"Available", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Available\")].status"}, apiextensions.CustomResourceColumnDefinition{Name:"Progressing", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].status"}, apiextensions.CustomResourceColumnDefinition{Name:"Since", Type:"date", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].lastTransitionTime"}, apiextensions.CustomResourceColumnDefinition{Name:"Status", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].message"}}}}: per-version schemas may not all be set to identical values (top-level validation should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1", Served:true, Storage:true, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(0xc0484a4218), Subresources:(*apiextensions.CustomResourceSubresources)(0xc0102cd980), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition{apiextensions.CustomResourceColumnDefinition{Name:"Version", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.history[?(@.state==\"Completed\")].version"}, apiextensions.CustomResourceColumnDefinition{Name:"Available", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Available\")].status"}, apiextensions.CustomResourceColumnDefinition{Name:"Progressing", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].status"}, apiextensions.CustomResourceColumnDefinition{Name:"Since", Type:"date", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].lastTransitionTime"}, apiextensions.CustomResourceColumnDefinition{Name:"Status", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].message"}}}}: per-version subresources may not all be set to identical values (top-level subresources should be used instead), spec.versions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1", Served:true, Storage:true, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(0xc0484a4218), Subresources:(*apiextensions.CustomResourceSubresources)(0xc0102cd980), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition{apiextensions.CustomResourceColumnDefinition{Name:"Version", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.history[?(@.state==\"Completed\")].version"}, apiextensions.CustomResourceColumnDefinition{Name:"Available", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Available\")].status"}, apiextensions.CustomResourceColumnDefinition{Name:"Progressing", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].status"}, apiextensions.CustomResourceColumnDefinition{Name:"Since", Type:"date", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].lastTransitionTime"}, apiextensions.CustomResourceColumnDefinition{Name:"Status", Type:"string", Format:"", Description:"", Priority:0, JSONPath:".status.conditions[?(@.type==\"Progressing\")].message"}}}}: per-version additionalPrinterColumns may not all be set to identical values (top-level additionalPrinterColumns should be used instead)] 
```

**Comment by sttts** [comment]
Any progress here?

**Comment by LalatenduMohanty** [comment]
Last e2e-agnostic-operator failure looks unrelated. 
```
 ERRO[2021-05-25T19:22:02Z] Some steps failed:                           
ERRO[2021-05-25T19:22:02Z]   * could not run steps: step e2e-agnostic-operator failed: ["e2e-agnostic-operator" pre steps failed: "e2e-agnostic-operator" pod "e2e-agnostic-operator-ipi-install-install" failed: the pod ci-op-q4vcrfnh/e2e-agnostic-operator-ipi-install-install failed after 50s (failed containers: test): ContainerFailed one or more containers exited 
ERRO[2021-05-25T19:22:02Z] Container test exited with code 1, reason Error 
ERRO[2021-05-25T19:22:02Z] ---                                          
ERRO[2021-05-25T19:22:02Z] Installing from release registry.build01.ci.openshift.org/ci-op-q4vcrfnh/release@sha256:6d42d3893a4aee8f1dbe513f976b782ebc9f62225ea3871a1701612fd54b5703 
ERRO[2021-05-25T19:22:02Z] level=info msg=Credentials loaded from file "/var/run/secrets/ci.openshift.io/cluster-profile/osServicePrincipal.json" 
ERRO[2021-05-25T19:22:02Z] level=fatal msg=failed to fetch Master Machines: failed to load asset "Install Config": platform.azure.region: Internal error: failed to retrieve available regions: failed to list locations: subscriptions.Client#ListLocations: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded 
ERRO[2021-05-25T19:22:02Z] Setup phase finished, prepare env for next steps 
ERRO[2021-05-25T19:22:02Z] Copying log bundle...                        
ERRO[2021-05-25T19:22:02Z] Removing REDACTED info from log...           
ERRO[2021-05-25T19:22:02Z] Copying required artifacts to shared dir     
ERRO[2021-05-25T19:22:02Z] cp: cannot stat '/tmp/installer/auth/kubeconfig': No such file or directory 
ERRO[2021-05-25T19:22:02Z] cp: cannot stat '/tmp/installer/auth/kubeadmin-password': No such file or directory 
ERRO[2021-05-25T19:22:02Z] cp: cannot stat '/tmp/installer/metadata.json': No such file or directory 
ERRO[2021-05-25T19:22:02Z] {"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-05-25T19:17:12Z"} 
ERRO[2021-05-25T19:22:02Z] error: failed to execute wrapped command: exit status 1 
```

**Review by wking — APPROVED** [review]
/lgtm
/hold cancel

Neither the d3fe8714af nor the f8f5fd8e1cd commit messages explain how the changes were generated, which will make it a bit harder on whoever has to repeat this process next time.  But fixing that may not be worth running a full new round of CI.  [The `etcdHighNumberOfLeaderChanges` alert][1] is unrelated:

/override ci/prow/e2e-agnostic-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/567/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1398003534602964992

**Pull request merged**
