### PR TITLE
Bug 1940652: Bump logging to --v=5

### PR DESCRIPTION
**Pull request by jottofar**
To pick up all the .V(5) logging in pkg/cvo/sync_worker.go.  I'm
especially interested in syncStatus logging that logs Generation
to help debug issue [1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1915559

### CODE REVIEW

**Comment by jottofar** [comment]
/retitle Bug 1915559: Bump logging to --v=5

**Comment by jottofar** [comment]
/retitle Bug 1940652: Bump logging to --v=5

**Comment by jwforres** [comment]
This pull request was not picked by patch manager for the current z-stream window (%!s(float32=0.2)-4.5 z-stream is in maintenance - skipping medium severity bugs. Reach out to the patch manager if a policy override is needed.).

Score: %!f(MISSING)
Reason: %!s(MISSING)

**NOTE**: This message is automatically generated, if you have questions please ask on #forum-release

**Pull request merged**
