### PR TITLE
OCPBUGS-20744: [4.13] Bump http-related deps

### PR DESCRIPTION
**Pull request by petr-muller**
Created with:

```console
$ go get golang.org/x/net@v0.17.0
$ go get k8s.io/apimachinery@v0.26.10
$ go get k8s.io/apiserver@v0.26.10
$ go get github.com/openshift/library-go@release-4.13
$ go mod tidy
$ go mod vendor
```

Second commit makes linters happy in as minimally invasive way as possible:

```
- Replace the easy cases of deprecated method usage
  - `pointer.BoolPtr` -> `pointer.Bool`
  - `sets.String` -> `sets.Set[string]`
- Explicitly ignore several return values
```

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Comment by jiajliu** [comment]
regression test against the pr pass.
/label qe-approved

**Pull request merged**
