### PR TITLE
Bump openshift/api

### PR DESCRIPTION
**Pull request by creydr**
Bump openshift/api and its k8s dependencies

**Hints for reviewers:**
I adjusted the unit tests for the new capabilities.
The `TestCVO_InitImplicitlyEnabledCaps` seemed to be a bit flacky, because of some unordered slice (`ImplicitlyEnabledCaps`):
```
--- FAIL: TestCVO_InitImplicitlyEnabledCaps (0.00s)
    cvo_scenarios_test.go:3891: unexpected status item 0
        Expected: cvo.SyncWorkerStatus{Generation:1, Failure:error(nil), Done:0, Total:3, Completed:0, Reconciling:false, Initial:false, VersionHash:"DL-FFQ2Uem8=", LastProgress:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Actual:v1.Release{Version:"1.0.1-abc", Image:"image/image:1", URL:"https://example.com/v1.0.1-abc", Channels:[]string(nil)}, Verified:false, loadPayloadStatus:cvo.LoadPayloadStatus{Step:"PayloadLoaded", Message:"Payload loaded version=\"1.0.1-abc\" image=\"image/image:1\"", Failure:error(nil), Update:v1.Update{Version:"1.0.1-abc", Image:"image/image:1", Force:false}, Verified:false, LastTransitionTime:time.Time{wall:0x0, ext:62135596801, loc:(*time.Location)(0x2c9d820)}}, CapabilitiesStatus:cvo.CapabilityStatus{Status:v1.ClusterVersionCapabilitiesStatus{EnabledCapabilities:[]v1.ClusterVersionCapability{"Console", "Insights", "baremetal", "marketplace", "openshift-samples"}, KnownCapabilities:[]v1.ClusterVersionCapability{"Console", "Insights", "baremetal", "marketplace", "openshift-samples"}}, ImplicitlyEnabledCaps:[]v1.ClusterVersionCapability{"marketplace", "openshift-samples", "Console", "Insights"}}}
        Actual: cvo.SyncWorkerStatus{Generation:1, Failure:error(nil), Done:0, Total:3, Completed:0, Reconciling:false, Initial:false, VersionHash:"DL-FFQ2Uem8=", LastProgress:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Actual:v1.Release{Version:"1.0.1-abc", Image:"image/image:1", URL:"https://example.com/v1.0.1-abc", Channels:[]string(nil)}, Verified:false, loadPayloadStatus:cvo.LoadPayloadStatus{Step:"PayloadLoaded", Message:"Payload loaded version=\"1.0.1-abc\" image=\"image/image:1\"", Failure:error(nil), Update:v1.Update{Version:"1.0.1-abc", Image:"image/image:1", Force:false}, Verified:false, LastTransitionTime:time.Time{wall:0x0, ext:62135596801, loc:(*time.Location)(0x2c9d820)}}, CapabilitiesStatus:cvo.CapabilityStatus{Status:v1.ClusterVersionCapabilitiesStatus{EnabledCapabilities:[]v1.ClusterVersionCapability{"Console", "Insights", "baremetal", "marketplace", "openshift-samples"}, KnownCapabilities:[]v1.ClusterVersionCapability{"Console", "Insights", "baremetal", "marketplace", "openshift-samples"}}, ImplicitlyEnabledCaps:[]v1.ClusterVersionCapability{"openshift-samples", "Console", "Insights", "marketplace"}}}
```
in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/817/pull-ci-openshift-cluster-version-operator-master-unit/1557028368216494080/artifacts/test/build-log.txt
(can be seen as the unit tests in this PR are flaky before commit 8278319c2b03fc9812fc1847cb9c6eb9afd9b87a).

So I added a sort in the test before comparing the actual with expected status: https://github.com/openshift/cluster-version-operator/blob/0fa94e7ddf23022b7bb18a1d72645c6ecee5d4c2/pkg/cvo/cvo_scenarios_test.go#L3933 in 8278319c2b03fc9812fc1847cb9c6eb9afd9b87a

### CODE REVIEW

**Comment by creydr** [comment]
/assign @lalatendumohanty
I was able to fix the flaky unit test. Could you PTAL?
Thanks in advance

**Comment by rluders** [comment]
Well, this one seems to contain the changes from #817 and #820, so I guess that we want to proceed by getting this one merged. Don't we?

@creydr @jottofar @wking WDYT?

**Comment by LalatenduMohanty** [comment]
The PR looks fine to me except the sequence of commits. The commit for `Migrate to ConfigMapsLeasesResourceLock` should be after the API bump commit

**Review by LalatenduMohanty — CHANGES_REQUESTED** [review]
The PR looks fine to me except the sequence of commits. The commit for Migrate to ConfigMapsLeasesResourceLock should be after the API bump commit

**Comment by creydr** [comment]
> The PR looks fine to me except the sequence of commits. The commit for Migrate to ConfigMapsLeasesResourceLock should be after the API bump commit

The reason for having it before was that we would always have a "working" build. (the ConfigMapLock is not available in the new dependencies)

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request closed without merging**
