### PR TITLE
Bug 1883705: *: Move to klog v2

### PR DESCRIPTION
**Pull request by wking**
When we moved to 0.19 Kube tooling in ef236c385d (#420), the tooling moved to klog v2.  Port our local klog consumers so we don't have to worry about configuring multiple klogs.

Generated with:

```console
$ sed -i 's|^go 1.13|go 1.15|' go.mod
$ sed -i 's|k8s.io/klog v1.0.0|k8s.io/klog/v2 v2.3.0|' go.mod
$ sed -i 's|"k8s.io/klog"|"k8s.io/klog/v2"|' $(git grep -l k8s.io/klog cmd lib pkg)
$ sed -i 's|klog.V(\([0-9]\)) |klog.V(\1).Enabled() |' $(git grep -l klog.V cmd lib pkg)
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```

using:

```console
$ go version
go version go1.15.2 linux/amd64
```

The change to Go 1.15 catches us up with 1d9a31926d (#457).

### CODE REVIEW

**Review by vrutkovs — APPROVED** [review]
/lgtm

**Review by oshoval — COMMENTED** [review]
Looking on the snippet,
aint the commands with `grep -l` will stop on the first one, (according man grep) and they should sed on all the files ?
```
$ sed -i 's|^go 1.13|go 1.15|' go.mod
$ sed -i 's|k8s.io/klog v1.0.0|k8s.io/klog/v2 v2.3.0|' go.mod
$ sed -i 's|"k8s.io/klog"|"k8s.io/klog/v2"|' $(git grep -l k8s.io/klog cmd lib pkg)
$ sed -i 's|klog.V(\([0-9]\)) |klog.V(\1).Enabled() |' $(git grep -l klog.V cmd lib pkg)
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```

**Comment by vrutkovs** [comment]
>aint the commands with grep -l will stop on the first one

`git grep -l` doesn't stop on the first one

**Comment by wking** [comment]
[e2e][1]:

```

level=error msg="Error: Error when reading or editing ComputeRouterNat \"openshift-gce-devel-ci/us-east1/ci-op-7jn3ir6n-11cd2-gw5b7-router/ci-op-7jn3ir6n-11cd2-gw5b7-nat-worker\": googleapi: Error 403: Quota exceeded for quota group 'ReadGroup' and limit 'Read requests per 100 seconds' of service 'compute.googleapis.com' for consumer 'project_number:1053217076791'., rateLimitExceeded" 
```

So that's not specific to this PR.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/462/pull-ci-openshift-cluster-version-operator-master-e2e/1311354194766073856

**Comment by wking** [comment]
[e2e][1] had some Kube-API components alerting:

```
        "ALERTS{alertname!~\"Watchdog|AlertmanagerReceiversNotConfigured|PrometheusRemoteWriteDesiredShards\",alertstate=\"firing\",severity!=\"info\"} >= 1": {
            s: "promQL query: ALERTS{alertname!~\"Watchdog|AlertmanagerReceiversNotConfigured|PrometheusRemoteWriteDesiredShards\",alertstate=\"firing\",severity!=\"info\"} >= 1 had reported incorrect results:\n[{\"metric\":{\"__name__\":\"ALERTS\",\"alertname\":\"KubeAPIDown\",\"alertstate\":\"firing\",\"severity\":\"critical\"},\"value\":[1601490640.792,\"1\"]},{\"metric\":{\"__name__\":\"ALERTS\",\"alertname\":\"KubeControllerManagerDown\",\"alertstate\":\"firing\",\"severity\":\"critical\"},\"value\":[1601490640.792,\"1\"]},{\"metric\":{\"__name__\":\"ALERTS\",\"alertname\":\"KubeSchedulerDown\",\"alertstate\":\"firing\",\"severity\":\"critical\"},\"value\":[1601490640.792,\"1\"]}]",
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/462/pull-ci-openshift-cluster-version-operator-master-e2e/1311360738312327168

**Pull request merged**
