### PR TITLE
OCPBUGS-27822: Revert "[release-4.14] OCPBUGS-27175: clusterOperatorBuilder: Reconcile metadata on COs"

### PR DESCRIPTION
**Pull request by wking**
Reverts openshift/cluster-version-operator#1021

Possibly related to [OCPBUGS-27822](https://issues.redhat.com/browse/OCPBUGS-27822)?  Let's see...

/hold

### CODE REVIEW

**Comment by wking** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-sdn-techpreview
/payload-job periodic-ci-openshift-release-master-nightly-4.14-e2e-vsphere-ovn-techpreview

**Comment by wking** [comment]
[Sandbox failures][1] are orthogonal.

/override ci/prow/e2e-agnostic-ovn

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-version-operator/1028/pull-ci-openshift-cluster-version-operator-release-4.14-e2e-agnostic-ovn/1749938432903221248

**Comment by wking** [comment]
[Both tech-preview rehearsals passed][1], so this revert successfully greens that up.  As discussed in [OCPBUGS-27822](https://issues.redhat.com/browse/OCPBUGS-27822), I think the cache-corruption issue has existed before, and OCPBUGS-27822 just gave us the ClusterOperator churn we needed to notice it.  But "remove the ClusterOperator churn" tucks the corruption back under the rug, and we can go poke it again whenever we like even if we revert the ClusterOperator metadata management in this pull.

/hold cancel

[1]: https://pr-payload-tests.ci.openshift.org/runs/ci/8345b7a0-ba48-11ee-962c-54f68a4c112b-0

**Comment by petr-muller** [comment]
IIUC the Slack thread correctly then this is a hit and we're vulnerable in master, we simply do not have COs with namespace set that would make CVO go into the hotloop and give the client cache the opportunity to corrupt:

```
 [sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster should have important platform topology metrics [apigroup:config.openshift.io] [Skipped:Disconnected] [Suite:openshift/conformance/parallel] expand_more
: [sig-instrumentation] Prometheus [apigroup:image.openshift.io] when installed on the cluster should start and expose a secured proxy and unsecured metrics [apigroup:config.openshift.io] [Skipped:Disconnected] [Suite:openshift/conformance/parallel] expand_more
```

**Pull request merged**
