### PR TITLE
OCPBUGS-20729: [4.12] Bump http-related deps

### PR DESCRIPTION
**Pull request by petr-muller**
Created with:

```console
$ go get golang.org/x/net@v0.17.0
$ go get k8s.io/apimachinery@v0.25.15
$ go get k8s.io/apiserver@v0.25.15
$ go get github.com/openshift/library-go@release-4.12
$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Comment by jiajliu** [comment]
pre-merge test pass.
/label qe-approved

**Pull request merged**
