### PR TITLE
OCPBUGS-45328: deps: bump golang.org/x/net to 0.31.0

### PR DESCRIPTION
**Pull request by petr-muller**
Created by:

```console
$ go get -u golang.org/x/net
go: upgraded golang.org/x/crypto v0.21.0 => v0.29.0
go: upgraded golang.org/x/net v0.23.0 => v0.31.0
go: upgraded golang.org/x/sys v0.18.0 => v0.27.0
go: upgraded golang.org/x/term v0.18.0 => v0.26.0
go: upgraded golang.org/x/text v0.14.0 => v0.20.0

$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Comment by DavidHurta** [comment]
/lgtm

Let's see what the CI is thinking.

**Review by DavidHurta — APPROVED** [review]

**Comment by jiajliu** [comment]
no qe work needed on this pr, so

/label cherry-pick-approved
/label qe-approved

**Pull request merged**
