### PR TITLE
pkg/cvo: add test utility functions

### PR DESCRIPTION
**Pull request by jottofar**
that allow checks of an entire structure or one of it's sub-structures (using generics). Also added is the ability to check for a single
status, e.g. the "final" status, by specifying a condition to indicate some state such as finality, e.g. Completed==3. There are also some functions that allow a test to wait for a particular condition, e.g. payload load status is "PayloadLoaded", before continuing.

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@jottofar the PR looks good to me except one nit pick,  can you update the commit message https://github.com/openshift/cluster-version-operator/pull/833/commits/d85b37656b31ef854eb2a5c58bd2396f4ea48e2d with steps about how you generated the files?

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
[Only failing `Prometheus when installed on the cluster should report telemetry if a cloud.openshift.com token is present`][1] is orthogonal (described in openshift/release#32249):

/override ci/prow/e2e-agnostic

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/833/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic/1569716063334043648

**Comment by wking** [comment]
[Only failing `Application behind service load balancer with PDB remains available using new connections`][1] is orthogonal:

/override ci/prow/e2e-agnostic-upgrade-into-change

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/833/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade-into-change/1569716063401152512

**Pull request merged**
