### PR TITLE
Bug 1921180: pkg/cvo/sync_worker.go: Ignore work changes during init

### PR DESCRIPTION
**Pull request by jottofar**
Also adds logging of work change details.

### CODE REVIEW

**Comment by wking** [comment]
With [`cherry-pick-diff`](https://github.com/openshift/cluster-version-operator/files/5882798/cherry-pick-diff.txt):

```console
$ cherry-pick-diff origin/release-4.6..origin/pr/506 origin/master
213726df -> bea62418 Bug 1905221: pkg/cvo/sync_worker.go: Ignore work changes during init
f24622bb -> 85fb1ee6 pkg/cvo/sync_worker.go: log work change details
...
```

with no meaningful changes between the original and picked-back commits.

/lgtm
/retest

**Comment by wking** [comment]
Now:

```console
$ cherry-pick-diff origin/release-4.6..origin/pr/506 origin/master
1a435303 -> 6675fa22 pkg/cvo/sync_worker.go: Fix Warning and Info log statements to handle arguments
213726df -> bea62418 Bug 1905221: pkg/cvo/sync_worker.go: Ignore work changes during init
f24622bb -> 85fb1ee6 pkg/cvo/sync_worker.go: log work change details

...no meaningful changes between the original and picked-back commits...
```

/lgtm

**Comment by derekwaynecarr** [comment]
(Patch-Manager) approved, met criteria.

**Pull request merged**
