### PR TITLE
pkg/payload: De-noise 'excluding ...' logs

### PR DESCRIPTION
**Pull request by wking**
Pull in openshift/library-go@0cf7e72a66 (openshift/library-go#1547), to tighten down long log lines like:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/950/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn/1670881314321993728/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-8598f95688-jswk8_cluster-version-operator.log | grep ' excluding ' | head -n1
I0619 20:21:07.321663       1 payload.go:210] excluding {0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml {apiextensions.k8s.io CustomResourceDefinition apiservers.config.openshift.io } {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{...
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-ingress-operator/950/pull-ci-openshift-cluster-ingress-operator-master-e2e-aws-ovn/1670881314321993728/artifacts/e2e-aws-ovn/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-8598f95688-jswk8_cluster-version-operator.log | grep ' excluding ' | head -n1 | wc
        1    1361   13998
```

Generated with:

```console
$ go get -u github.com/openshift/library-go
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```

using:

```console
$ go version
go version go1.19.5 linux/amd64
```

### CODE REVIEW

**Comment by wking** [comment]
[e2e-agnostic-ovn][1] had some unrelated disruption issues,  but doesn't seem to have denoised the relevant logs:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/945/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1671905719714058240/artifacts/e2e-agnostic-ovn/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-578685bc8-h5c8j_cluster-version-operator.log | grep excluding | head -n1 | wc
      1    1361   13998
```

I've pushed 6846a312 -> 1d7d28d5 to try an explicit `String` call.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/945/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1671905719714058240

**Comment by wking** [comment]
[e2e-agnostic-ovn][1] looks much cleaner now:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/945/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1671990094287867904/artifacts/e2e-agnostic-ovn/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-7cf9ff57c8-8xqp6_cluster-version-operator.log | grep excluding | head -n2
I0622 22:02:29.945593       1 payload.go:210] excluding Filename: "0000_10_config-operator_01_apiserver-CustomNoUpgrade.crd.yaml" Group: "apiextensions.k8s.io" Kind: "CustomResourceDefinition" Name: "apiservers.config.openshift.io": "Default" is required, and release.openshift.io/feature-set=CustomNoUpgrade
I0622 22:02:29.952420       1 payload.go:210] excluding Filename: "0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml" Group: "apiextensions.k8s.io" Kind: "CustomResourceDefinition" Name: "apiservers.config.openshift.io": "Default" is required, and release.openshift.io/feature-set=TechPreviewNoUpgrade
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/945/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-ovn/1671990094287867904

**Review by petr-muller — APPROVED** [review]
```
sig-node] nodes should not go unready after being upgraded and go unready only once
```
^^^ unlikely to be caused by CVO
/override ci/prow/e2e-agnostic-ovn-upgrade-out-of-change

**Pull request merged**
