### PR TITLE
OCPBUGS-22408: pkg/clusterconditions/promql: Warm cache with 1s delay

### PR DESCRIPTION
**Pull request by wking**
Picking #974 and #980 back to 4.12.

### CODE REVIEW

**Comment by wking** [comment]
And I've added a new-for-this-backport unit-test tweak in b6cffae1 to avoid [this failure][1]:

```
    --- FAIL: TestCVO_UpgradeFailedPayloadLoadWithCapsChanges (2.01s)
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:1919: TestCVO_UpgradeFailedPayloadLoadWithCapsChanges:init: Clearing all status...
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:1970: TestCVO_UpgradeFailedPayloadLoadWithCapsChanges:final sync: Clearing all status...
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3961: Waiting for condition
        cvo_scenarios_test.go:3964: saw too many sync events of the wrong form
```

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/988/pull-ci-openshift-cluster-version-operator-release-4.12-unit/1717260314141003776

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
[Slightly high disruption][1], unrelated to my change which the job doesn't even excercise.

/test e2e-agnostic-ovn-upgrade-into-change

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/988/pull-ci-openshift-cluster-version-operator-release-4.12-e2e-agnostic-ovn-upgrade-into-change/1720155131590217728

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request merged**
