### PR TITLE
OCPBUGS-45327: deps: bump golang.org/x/net to 0.31.0

### PR DESCRIPTION
**Pull request by petr-muller**
Created by:

```console
$ go get -u golang.org/x/net
go: upgraded golang.org/x/crypto v0.27.0 => v0.29.0
go: upgraded golang.org/x/net v0.29.0 => v0.31.0
go: upgraded golang.org/x/sync v0.8.0 => v0.9.0
go: upgraded golang.org/x/sys v0.25.0 => v0.27.0
go: upgraded golang.org/x/term v0.24.0 => v0.26.0
go: upgraded golang.org/x/text v0.18.0 => v0.20.0

$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Comment by DavidHurta** [comment]
/lgtm

Let's see what the CI is thinking.

**Comment by petr-muller** [comment]
/override e2e-agnostic-operator e2e-aws-ovn-techpreview

These two jobs actually fully succeeded, they only failed at the end when ci-operator failed to release the lease because of  the Boskos outage:

```
INFO[2024-12-03T14:24:44Z] Step phase post succeeded after 11m40s.      
INFO[2024-12-03T14:24:44Z] Releasing leases for test e2e-agnostic-operator 
WARN[2024-12-03T14:41:33Z] Failed to update lease "centralus--azure4-quota-slice-25"  error=no resource name centralus--azure4-quota-slice-25
WARN[2024-12-03T14:41:33Z] Failed to update lease "centralus--azure4-quota-slice-25"  error=no resource name centralus--azure4-quota-slice-25
INFO[2024-12-03T14:41:33Z] Ran for 2h4m49s                              
ERRO[2024-12-03T14:41:33Z] Some steps failed:                           
ERRO[2024-12-03T14:41:33Z] 
  * could not run steps: step e2e-agnostic-operator failed: [status 502 Bad Gateway, statusCode 502 releasing centralus--azure4-quota-slice-25, status 401 Unauthorized, statusCode 401 releasing centralus--azure4-quota-slice-25] 
```

HyperShift jobs failed to _start_ testing because of the Boskos outage, so I am not overriding these

**Comment by petr-muller** [comment]
/override ci/prow/e2e-agnostic-operator ci/prow/e2e-aws-ovn-techpreview

**Pull request merged**
