### PR TITLE
Dockerfile*: Bump to Go 1.14

### PR DESCRIPTION
**Pull request by wking**
Other components have already moved, such as the installer in openshift/installer@46a5f49709 (openshift/installer#3723).  This will make enforcing Go 1.14 formatting more consistent, per discussion [here][1].

[1]: https://github.com/openshift/cluster-version-operator/pull/411/files#r458821597

### CODE REVIEW

**Comment by wking** [comment]
[Unrelated PDB disruption][1].

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/414/pull-ci-openshift-cluster-version-operator-master-e2e-upgrade/1286069158861082624

**Comment by wking** [comment]
[All][1] [of][2] [the][3] [last][4] [five][5] update tests died on `Application behind service load balancer with PDB is not disrupted`.  Should we `/override`?  I can't see how a CVO pivot to 1.14 would be related.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/414/pull-ci-openshift-cluster-version-operator-master-e2e-upgrade/1286337088559517696
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/414/pull-ci-openshift-cluster-version-operator-master-e2e-upgrade/1286305397203800064
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/414/pull-ci-openshift-cluster-version-operator-master-e2e-upgrade/1286269407655366656
[4]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/414/pull-ci-openshift-cluster-version-operator-master-e2e-upgrade/1286232635739213824
[5]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/414/pull-ci-openshift-cluster-version-operator-master-e2e-upgrade/1286069158861082624

**Comment by vrutkovs** [comment]
+1 to override

**Pull request merged**
